### PR TITLE
Svgstore

### PR DESCRIPTION
**Pull request by kevinkace**

### CODE REVIEW

**Comment by kevinkace** [comment]
Makes sense.

For export:
- collapse whitespace

Some other cleanup for standard and export build:
- the source icons from icomoon have a `class="path1"`, can probably strip that
- remove `<?xml>` and `<!DOCTYPE>`?

**Comment by tivac** [comment]
The defaults in [svgo](https://www.npmjs.com/package/svgo) are probably sufficient to clean things up. Might need to ensure that it doesn't strip "unreferenced" defs since that's the entire file.

**Comment by kevinkace** [comment]
Cool, I'll check it out!

**Comment by kevinkace** [comment]
Update on a couple issues I'm still investigating.

1. svgstore isn't adding the `symbols` to `defs`, so you end up with `<defs />` before the first `symbol`.
2. svgo is collapsing whitespace, removing the empty `<defs />`, but [isn't removing class attrs](https://github.com/svg/svgo/issues/662).

**Comment by kevinkace** [comment]
Think I have the wrinkles ironed out, here's the output: https://gist.github.com/kevinkace/236131370394dedb7f9c30a39955fbbb

**Comment by tivac** [comment]
Build failures are 100% unrelated, so this is a huge :+1: from me. Thank you!

**Pull request merged**
